### ISSUE TITLE
[Bug]: Outline around active tab 

### ISSUE THREAD

**Issue by AlvaroVazquezJr** [edelvarden/material-fox-updated#71] opened 2024-09-03 15:57 UTC
### What happened?

After the 130 update, there is now a white outline around the active tab.

![image](https://github.com/user-attachments/assets/07e54dad-da22-49c3-823c-dc0001023cfd)

### Steps to reproduce

1. Open Firefox (updated to 130)
2. Observe outline on active tab.

### Additional info (Optional)

Firefox version: 130
Operating System: Windows 11

**Comment by edelvarden** [comment] 2024-09-05 20:00
Did you use the latest Material Fox version? I can't reproduce this issue because it was already fixed in #62

**Comment by kbc8090** [comment] 2024-09-07 13:44
That's likely one of your normal firefox themes causing that.  Had a similar problem so I decided to just use custom.css to theme rather than using userChrome.theme-default with random themes.

**Comment by AlvaroVazquezJr** [comment] 2024-09-19 01:42
> Did you use the latest Material Fox version? I can't reproduce this issue because it was already fixed in #62

You're totally right! Sorry, I must have copied my old chrome folder when I thought I was "pasting" my new one. Issue is good to close.

**Closed as completed** 2024-09-19 09:01 UTC
Labels: bug
